-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE cuti (
    id SERIAL PRIMARY KEY,
    lama_cuti integer,
    keterangan text,
    tanggal_cuti date,
    no_induk character varying(100) REFERENCES karyawan(no_induk) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX cuti_pkey ON cuti(id int4_ops);
